apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: worker
  name: worker
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: worker
    spec:
      containers:
      - image: pandaacademy/worker:1.0
        name: worker
        resources: {}
        env:
        - name: POSTGRES_USER
          value: "Userpostgreas"
        - name: POSTGRES_PASSWORD
          value: "PasswordUseraPostgresa"
        - name: DB_HOST
          value: "db-svc.database"
        - name: REDIS_HOST
          value: "redis-svc.database"
status: {}